package server

// Phase 19 Step 5 — backup scheduler tests.
//
// Coverage matrix:
//   - tryScheduledBackup happy path: produces a tarball, writes
//     stats sidecar with successes_total=1
//   - tryScheduledBackup with [backup].enabled=false: no-op, no
//     tarball, stats unchanged
//   - tryScheduledBackup mutex contention: second call while first
//     holds the lock returns immediately (skipped, not queued)
//   - tryScheduledBackup failure: increments failures_total, stores
//     last_error_msg, no tarball
//   - skip-if-idle: first tick runs (no baseline); second tick on
//     idle data is skipped
//   - applyRetention: count cap correctly prunes oldest tarballs
//   - applyRetention: age cap correctly prunes ancient tarballs
//   - applyRetention: OR semantics — either cap triggers deletion
//   - applyRetention: ignores non-tarball files in dest_dir
//   - ReadBackupStatsForCLI: missing file → zeros; valid file → parsed
//   - resolveBackupDestDir: absolute / relative / empty handling
//   - isBackupTarball: correct prefix+suffix matching

import (
	"errors"
	"fmt"
	"io"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/brushtailmedia/sshkey-chat/internal/config"
)

// newSchedulerTestServer builds a Server with a writable dataDir +
// configDir, ready to invoke tryScheduledBackup against. Differs
// from newTestServer in that it sets backupStartupGracePeriod=0
// (test cleanup restores the previous value) so the scheduler
// doesn't pause for 60s when started directly.
func newSchedulerTestServer(t *testing.T) *Server {
	t.Helper()
	prev := SetBackupStartupGracePeriod(0)
	t.Cleanup(func() { SetBackupStartupGracePeriod(prev) })

	configDir := t.TempDir()
	dataDir := t.TempDir()

	if err := os.WriteFile(filepath.Join(configDir, "server.toml"), []byte(`
[server]
port = 2222
bind = "127.0.0.1"

[server.auto_revoke]
enabled = false

[backup]
enabled = true
interval = "24h"
dest_dir = "backups"
retention_count = 5
retention_age = "168h"
compress = true
include_config_files = true
`), 0644); err != nil {
		t.Fatalf("write server.toml: %v", err)
	}
	if err := os.WriteFile(filepath.Join(configDir, "rooms.toml"), []byte{}, 0644); err != nil {
		t.Fatalf("write rooms.toml: %v", err)
	}
	// host_key is generated by Server.New (loadOrGenerateHostKey)
	// when missing; we don't pre-write a fake one because the server
	// would fail to parse it.

	cfg, err := config.Load(configDir)
	if err != nil {
		t.Fatalf("load config: %v", err)
	}
	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	s, err := New(cfg, logger, dataDir)
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	t.Cleanup(func() {
		if s.store != nil {
			s.store.Close()
		}
		// Don't run Close() — tests don't start ListenAndServe so
		// the listener fields are nil and Close paths assume them.
		// Just remove the lockfile so the next New on same dir works.
		_ = os.Remove(filepath.Join(dataDir, lockfileName))
	})
	return s
}

// -------- tryScheduledBackup --------

func TestTryScheduledBackup_HappyPath(t *testing.T) {
	s := newSchedulerTestServer(t)

	s.tryScheduledBackup()

	// Stats sidecar should show 1 success.
	if got := s.BackupSuccessesTotal(); got != 1 {
		t.Errorf("successes_total = %d, want 1", got)
	}
	if got := s.BackupFailuresTotal(); got != 0 {
		t.Errorf("failures_total = %d, want 0", got)
	}

	// A tarball should exist under dataDir/backups.
	destDir := filepath.Join(s.dataDir, "backups")
	entries, err := os.ReadDir(destDir)
	if err != nil {
		t.Fatalf("ReadDir %s: %v", destDir, err)
	}
	tarballs := 0
	for _, e := range entries {
		if isBackupTarball(e.Name()) {
			tarballs++
		}
	}
	if tarballs != 1 {
		t.Errorf("expected 1 tarball, got %d (entries: %v)", tarballs, entries)
	}
}

func TestTryScheduledBackup_DisabledIsNoop(t *testing.T) {
	s := newSchedulerTestServer(t)
	// Flip enabled off in the loaded config.
	s.cfg.Server.Backup.Enabled = false

	s.tryScheduledBackup()

	if got := s.BackupSuccessesTotal(); got != 0 {
		t.Errorf("disabled scheduler should not record success, got %d", got)
	}
	if got := s.BackupFailuresTotal(); got != 0 {
		t.Errorf("disabled scheduler should not record failure, got %d", got)
	}
	// No tarball written.
	if _, err := os.Stat(filepath.Join(s.dataDir, "backups")); err == nil {
		entries, _ := os.ReadDir(filepath.Join(s.dataDir, "backups"))
		for _, e := range entries {
			if isBackupTarball(e.Name()) {
				t.Errorf("tarball written despite enabled=false: %s", e.Name())
			}
		}
	}
}

func TestTryScheduledBackup_MutexContention(t *testing.T) {
	s := newSchedulerTestServer(t)

	// Hold the mutex from one goroutine; second tryScheduledBackup
	// must return immediately without producing a tarball.
	s.backupMu.Lock()
	defer s.backupMu.Unlock()

	done := make(chan struct{})
	go func() {
		s.tryScheduledBackup()
		close(done)
	}()
	select {
	case <-done:
		// Fast — TryLock skipped as expected.
	case <-time.After(2 * time.Second):
		t.Fatal("tryScheduledBackup blocked on mutex; expected fast skip via TryLock")
	}

	if got := s.BackupSuccessesTotal(); got != 0 {
		t.Errorf("contended call should skip without recording success, got %d", got)
	}
}

func TestTryScheduledBackup_FailureIncrementsCounter(t *testing.T) {
	s := newSchedulerTestServer(t)
	// Force a failure: remove the host_key so backup.Run aborts on
	// the required-file check (IncludeConfigFiles=true by default).
	if err := os.Remove(filepath.Join(s.cfg.Dir, "host_key")); err != nil {
		t.Fatalf("remove host_key: %v", err)
	}

	s.tryScheduledBackup()

	if got := s.BackupFailuresTotal(); got != 1 {
		t.Errorf("failures_total = %d, want 1", got)
	}
	if got := s.BackupSuccessesTotal(); got != 0 {
		t.Errorf("successes_total = %d, want 0", got)
	}

	// Verify last_error_msg captured.
	stats := s.readBackupStats()
	if stats.LastErrorMsg == "" {
		t.Error("LastErrorMsg empty after failure")
	}
	if !strings.Contains(stats.LastErrorMsg, "host_key") {
		t.Errorf("LastErrorMsg = %q, expected to mention host_key", stats.LastErrorMsg)
	}
}

// -------- skip-if-idle --------

func TestTryScheduledBackup_SkipIfIdle(t *testing.T) {
	s := newSchedulerTestServer(t)

	// First tick runs (no baseline yet).
	s.tryScheduledBackup()
	if got := s.BackupSuccessesTotal(); got != 1 {
		t.Fatalf("first tick: successes = %d, want 1", got)
	}

	// Second tick: data unchanged, skip should fire.
	s.tryScheduledBackup()
	if got := s.BackupSuccessesTotal(); got != 1 {
		t.Errorf("second tick on idle data: successes = %d, want still 1 (skipped)", got)
	}
}

func TestTryScheduledBackup_SkipIfIdle_DisabledMakesAllTicksRun(t *testing.T) {
	s := newSchedulerTestServer(t)
	s.cfg.Server.Backup.SkipIfIdle = false

	s.tryScheduledBackup()
	s.tryScheduledBackup()

	if got := s.BackupSuccessesTotal(); got != 2 {
		t.Errorf("with skip_if_idle=false, second tick should run; successes = %d, want 2", got)
	}
}

func TestTryScheduledBackup_SkipIfIdle_FilesChangeRunsAgain(t *testing.T) {
	// Write activity in data/files/ should defeat skip_if_idle on
	// the next tick. This is the practical "user uploaded an
	// attachment between scheduled backups" case.
	s := newSchedulerTestServer(t)

	s.tryScheduledBackup()
	if got := s.BackupSuccessesTotal(); got != 1 {
		t.Fatalf("first tick: %d, want 1", got)
	}

	// Drop a fake attachment blob into data/files/ so the dir
	// mtime increments. Sleep briefly to ensure mtime resolution
	// catches the change (some filesystems have second-granularity
	// mtimes).
	filesDir := filepath.Join(s.dataDir, "data", "files")
	if err := os.MkdirAll(filesDir, 0755); err != nil {
		t.Fatalf("mkdir files: %v", err)
	}
	time.Sleep(20 * time.Millisecond)
	if err := os.WriteFile(filepath.Join(filesDir, "file_test_blob"), []byte("new attachment"), 0644); err != nil {
		t.Fatalf("write blob: %v", err)
	}
	time.Sleep(20 * time.Millisecond)

	s.tryScheduledBackup()
	if got := s.BackupSuccessesTotal(); got != 2 {
		t.Errorf("second tick with new attachment: successes = %d, want 2", got)
	}
}

// -------- applyRetention --------

// seedTarballsByAge writes N fake tarballs in dir with mtimes spaced
// at oneAgeStep apart, oldest-to-newest. Returns names in
// chronological order (oldest first). Used to test retention's
// sort-by-mtime + cap behavior.
func seedTarballsByAge(t *testing.T, dir string, count int, oneAgeStep time.Duration) []string {
	t.Helper()
	if err := os.MkdirAll(dir, 0755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	now := time.Now()
	var names []string
	for i := 0; i < count; i++ {
		// Spaced timestamps so sort by mtime is stable.
		ts := now.Add(-time.Duration(count-1-i) * oneAgeStep)
		name := fmt.Sprintf("backup-%s.tar.gz", ts.UTC().Format("20060102-150405"))
		path := filepath.Join(dir, name)
		if err := os.WriteFile(path, []byte("fake"), 0644); err != nil {
			t.Fatalf("write %s: %v", path, err)
		}
		if err := os.Chtimes(path, ts, ts); err != nil {
			t.Fatalf("chtimes %s: %v", path, err)
		}
		names = append(names, name)
	}
	return names
}

func TestApplyRetention_CountCap(t *testing.T) {
	dir := t.TempDir()
	// 8 tarballs spaced 1 hour apart. Retention: keep 3, no age cap.
	names := seedTarballsByAge(t, dir, 8, time.Hour)
	cfg := config.ParsedBackupConfig{RetentionCount: 3}

	if err := applyRetention(dir, cfg); err != nil {
		t.Fatalf("applyRetention: %v", err)
	}

	entries, _ := os.ReadDir(dir)
	if len(entries) != 3 {
		var got []string
		for _, e := range entries {
			got = append(got, e.Name())
		}
		t.Fatalf("expected 3 tarballs after retention, got %d: %v", len(entries), got)
	}
	// The 3 newest names should remain. names[0] is oldest, names[len-1] is newest.
	wantKept := map[string]bool{
		names[5]: true, names[6]: true, names[7]: true,
	}
	for _, e := range entries {
		if !wantKept[e.Name()] {
			t.Errorf("unexpected file kept: %s (expected newest 3)", e.Name())
		}
	}
}

func TestApplyRetention_AgeCap(t *testing.T) {
	dir := t.TempDir()
	// 5 tarballs spaced 2 hours apart. Retention: age cap 5h, no count cap.
	// → tarballs older than 5h are deleted.
	// Spacing 2h: ages are 8h, 6h, 4h, 2h, 0h. Older than 5h = 8h and 6h.
	seedTarballsByAge(t, dir, 5, 2*time.Hour)
	cfg := config.ParsedBackupConfig{RetentionAge: 5 * time.Hour}

	if err := applyRetention(dir, cfg); err != nil {
		t.Fatalf("applyRetention: %v", err)
	}

	entries, _ := os.ReadDir(dir)
	// Should have 3 left (4h, 2h, 0h).
	if len(entries) != 3 {
		var got []string
		for _, e := range entries {
			got = append(got, e.Name())
		}
		t.Errorf("expected 3 tarballs after age cap, got %d: %v", len(entries), got)
	}
}

func TestApplyRetention_BothCapsORSemantics(t *testing.T) {
	dir := t.TempDir()
	// 7 tarballs spaced 1h apart. count=10 (effectively no cap —
	// nothing exceeds the count), age=3h30m. Tarballs older than
	// 3h30m should go regardless of count. Half-hour offset keeps
	// the boundary unambiguous (no test-microsecond-drift risk).
	seedTarballsByAge(t, dir, 7, time.Hour)
	cfg := config.ParsedBackupConfig{
		RetentionCount: 10,                    // larger than total — count cap inactive
		RetentionAge:   3*time.Hour + 30*time.Minute, // age cap with clear boundary
	}

	if err := applyRetention(dir, cfg); err != nil {
		t.Fatalf("applyRetention: %v", err)
	}
	entries, _ := os.ReadDir(dir)
	// Ages from oldest are 6h,5h,4h,3h,2h,1h,0h. > 3h30m: 6h,5h,4h
	// (3 deletions). Keep 4.
	if len(entries) != 4 {
		var got []string
		for _, e := range entries {
			got = append(got, e.Name())
		}
		t.Errorf("with count=10 + age=3h30m on 7 tarballs spaced 1h: expected 4 kept, got %d: %v", len(entries), got)
	}
}

func TestApplyRetention_IgnoresNonTarballs(t *testing.T) {
	dir := t.TempDir()
	seedTarballsByAge(t, dir, 5, time.Hour)
	// Add a stats file and a random text file — neither should be touched.
	if err := os.WriteFile(filepath.Join(dir, ".backup-stats.json"), []byte("{}"), 0644); err != nil {
		t.Fatalf("seed stats: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "operator-notes.txt"), []byte("hello"), 0644); err != nil {
		t.Fatalf("seed notes: %v", err)
	}

	cfg := config.ParsedBackupConfig{RetentionCount: 1}
	if err := applyRetention(dir, cfg); err != nil {
		t.Fatalf("applyRetention: %v", err)
	}

	mustExist := []string{".backup-stats.json", "operator-notes.txt"}
	for _, name := range mustExist {
		if _, err := os.Stat(filepath.Join(dir, name)); err != nil {
			t.Errorf("retention deleted non-tarball %s: %v", name, err)
		}
	}
	// Tarball count should be 1.
	entries, _ := os.ReadDir(dir)
	tarballs := 0
	for _, e := range entries {
		if isBackupTarball(e.Name()) {
			tarballs++
		}
	}
	if tarballs != 1 {
		t.Errorf("expected 1 tarball after retention_count=1, got %d", tarballs)
	}
}

func TestApplyRetention_NoCapsKeepsAll(t *testing.T) {
	dir := t.TempDir()
	seedTarballsByAge(t, dir, 5, time.Hour)
	cfg := config.ParsedBackupConfig{} // both caps zero → no retention

	if err := applyRetention(dir, cfg); err != nil {
		t.Fatalf("applyRetention: %v", err)
	}
	entries, _ := os.ReadDir(dir)
	if len(entries) != 5 {
		t.Errorf("with both caps disabled: expected 5 tarballs, got %d", len(entries))
	}
}

// -------- ReadBackupStatsForCLI --------

func TestReadBackupStatsForCLI_MissingFileIsZero(t *testing.T) {
	dir := t.TempDir()
	failures, successes, lastSuccess, lastFailure, errMsg := ReadBackupStatsForCLI(dir)
	if failures != 0 || successes != 0 || !lastSuccess.IsZero() || !lastFailure.IsZero() || errMsg != "" {
		t.Errorf("missing file should yield zero stats; got fail=%d succ=%d ls=%v lf=%v err=%q",
			failures, successes, lastSuccess, lastFailure, errMsg)
	}
}

func TestReadBackupStatsForCLI_RoundTrip(t *testing.T) {
	s := newSchedulerTestServer(t)
	s.tryScheduledBackup() // produces a real success row

	failures, successes, lastSuccess, _, _ := ReadBackupStatsForCLI(s.dataDir)
	if failures != 0 {
		t.Errorf("failures = %d, want 0", failures)
	}
	if successes != 1 {
		t.Errorf("successes = %d, want 1", successes)
	}
	if lastSuccess.IsZero() {
		t.Error("lastSuccess should be populated")
	}
}

// -------- resolveBackupDestDir --------

func TestResolveBackupDestDir(t *testing.T) {
	cases := []struct {
		name        string
		configDest  string
		dataDir     string
		want        string
	}{
		{"empty falls to default", "", "/data", "/data/backups"},
		{"relative anchored to dataDir", "snapshots", "/data", "/data/snapshots"},
		{"absolute used as-is", "/mnt/archive", "/data", "/mnt/archive"},
		{"deeply relative", "a/b/c", "/data", "/data/a/b/c"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := resolveBackupDestDir(tc.configDest, tc.dataDir)
			if got != tc.want {
				t.Errorf("resolveBackupDestDir(%q, %q) = %q, want %q",
					tc.configDest, tc.dataDir, got, tc.want)
			}
		})
	}
}

// -------- isBackupTarball --------

func TestIsBackupTarball(t *testing.T) {
	cases := map[string]bool{
		"backup-20260419-143022.tar.gz":             true,
		"backup-20260419-143022-pre-upgrade.tar.gz": true,
		"backup-x.tar.gz":                           true,
		"backup.tar.gz":                             false, // missing dash
		"snapshot-20260419.tar.gz":                  false, // wrong prefix
		"backup-20260419-143022.tar":                false, // wrong suffix
		"backup-20260419-143022.tar.gz.tmp":         false, // partial backup
		".backup-stats.json":                        false,
		"":                                          false,
	}
	for name, want := range cases {
		if got := isBackupTarball(name); got != want {
			t.Errorf("isBackupTarball(%q) = %v, want %v", name, got, want)
		}
	}
}

// -------- truncateErr --------

func TestTruncateErr(t *testing.T) {
	if got := truncateErr("hello", 100); got != "hello" {
		t.Errorf("short string mangled: %q", got)
	}
	long := strings.Repeat("x", 300)
	got := truncateErr(long, 50)
	if len(got) != 50 {
		t.Errorf("truncated len = %d, want 50", len(got))
	}
	if !strings.HasSuffix(got, "...") {
		t.Errorf("truncated should end with '...', got %q", got)
	}
}

// -------- runBackupScheduler — integration-style smoke test --------

// TestRunBackupScheduler_StopsCleanlyOnDisabledConfig verifies that
// enabled=false causes the goroutine to exit immediately rather than
// running a no-op tick loop forever.
func TestRunBackupScheduler_StopsCleanlyOnDisabledConfig(t *testing.T) {
	s := newSchedulerTestServer(t)
	s.cfg.Server.Backup.Enabled = false

	done := make(chan struct{})
	go func() {
		s.runBackupScheduler()
		close(done)
	}()

	select {
	case <-done:
		// Good — exited fast.
	case <-time.After(2 * time.Second):
		// Need to stop it manually.
		close(s.backupSchedulerStop)
		t.Error("scheduler did not exit on enabled=false within 2s")
	}
}

// TestRunBackupScheduler_StopsOnSignal exercises the goroutine
// lifecycle: start with grace=0, immediate first backup runs,
// stop channel closes, scheduler exits.
func TestRunBackupScheduler_StopsOnSignal(t *testing.T) {
	s := newSchedulerTestServer(t)

	done := make(chan struct{})
	var wg sync.WaitGroup
	wg.Add(1)
	go func() {
		defer wg.Done()
		s.runBackupScheduler()
		close(done)
	}()

	// Wait for the immediate first backup to complete (a success
	// recorded means tryScheduledBackup ran).
	deadline := time.Now().Add(3 * time.Second)
	for time.Now().Before(deadline) {
		if s.BackupSuccessesTotal() >= 1 {
			break
		}
		time.Sleep(50 * time.Millisecond)
	}
	if got := s.BackupSuccessesTotal(); got < 1 {
		close(s.backupSchedulerStop)
		wg.Wait()
		t.Fatalf("first backup did not complete within 3s; successes = %d", got)
	}

	// Now signal stop.
	close(s.backupSchedulerStop)
	select {
	case <-done:
	case <-time.After(2 * time.Second):
		t.Error("scheduler did not exit on stop signal within 2s")
	}
}

// -------- writeBackupStats failure path --------

func TestWriteBackupStats_UnwritableDirIsLogged(t *testing.T) {
	// Construct a Server with a deliberately bogus dataDir so the
	// stats write fails. The scheduler must log a warning but not
	// crash. We can only verify "didn't crash" because the logger
	// is io.Discard; in production the warning would be visible.
	s := &Server{
		dataDir: "/nonexistent/path/that/definitely/does/not/exist",
		logger:  slog.New(slog.NewTextHandler(io.Discard, nil)),
	}
	// Should not panic.
	s.writeBackupStats(backupStats{FailuresTotal: 1})
}

// -------- error wrapping invariants --------

func TestRecordBackupFailure_PreservesError(t *testing.T) {
	s := newSchedulerTestServer(t)
	s.recordBackupFailure(errors.New("simulated boom"))
	stats := s.readBackupStats()
	if stats.FailuresTotal != 1 {
		t.Errorf("FailuresTotal = %d, want 1", stats.FailuresTotal)
	}
	if !strings.Contains(stats.LastErrorMsg, "simulated boom") {
		t.Errorf("LastErrorMsg = %q, want substring 'simulated boom'", stats.LastErrorMsg)
	}
	if stats.LastFailureUnix == 0 {
		t.Error("LastFailureUnix not populated")
	}
}
