package actionauth

import (
	"crypto/ed25519"
	"encoding/base64"
	"encoding/json"
	"os"
	"testing"

	"golang.org/x/crypto/ssh"
)

func TestVerifyDelete_RoundTripAndBinding(t *testing.T) {
	pub, priv, err := ed25519.GenerateKey(nil)
	if err != nil {
		t.Fatal(err)
	}
	const kind, ctx, msg = "room", "rm_abc", "msg_123"
	sig := ed25519.Sign(priv, BuildDeleteCanonical(kind, ctx, msg))

	if !VerifyDelete(pub, kind, ctx, msg, sig) {
		t.Fatal("valid signature must verify")
	}
	// Bound to each field — a change to kind, contextID, or msgID fails
	// (replay/cross-context/retarget blocked).
	if VerifyDelete(pub, "group", ctx, msg, sig) {
		t.Error("different kind must fail")
	}
	if VerifyDelete(pub, kind, "rm_other", msg, sig) {
		t.Error("different contextID must fail")
	}
	if VerifyDelete(pub, kind, ctx, "msg_other", sig) {
		t.Error("different msgID must fail")
	}
	// Different key fails (forgery blocked — actor bound by key selection).
	otherPub, _, _ := ed25519.GenerateKey(nil)
	if VerifyDelete(otherPub, kind, ctx, msg, sig) {
		t.Error("different key must fail")
	}
	// Malformed inputs must fail closed without panicking ed25519.Verify.
	if VerifyDelete(pub, kind, ctx, msg, []byte("not a real signature")) {
		t.Error("garbage signature must fail")
	}
	if VerifyDelete(ed25519.PublicKey("short"), kind, ctx, msg, sig) {
		t.Error("undersized pubkey must fail (and not panic)")
	}
}

func TestVerifyUnreact_RoundTripAndBinding(t *testing.T) {
	pub, priv, err := ed25519.GenerateKey(nil)
	if err != nil {
		t.Fatal(err)
	}
	const kind, ctx, rid = "room", "rm_general", "react_1"
	sig := ed25519.Sign(priv, BuildUnreactCanonical(kind, ctx, rid))

	if !VerifyUnreact(pub, kind, ctx, rid, sig) {
		t.Fatal("valid un-react signature must verify")
	}
	if VerifyUnreact(pub, "group", ctx, rid, sig) {
		t.Error("different kind must fail")
	}
	if VerifyUnreact(pub, kind, "rm_other", rid, sig) {
		t.Error("different context must fail")
	}
	if VerifyUnreact(pub, kind, ctx, "react_other", sig) {
		t.Error("different reaction_id must fail (replay/retarget blocked)")
	}
	otherPub, _, _ := ed25519.GenerateKey(nil)
	if VerifyUnreact(otherPub, kind, ctx, rid, sig) {
		t.Error("different key must fail")
	}
	// Domain tag present + must not cross-verify as delete:v1.
	if got := BuildUnreactCanonical(kind, ctx, rid); string(got[:len("unreact:v2")]) != "unreact:v2" {
		t.Errorf("missing unreact:v2 tag: %q", got)
	}
	if VerifyDelete(pub, kind, ctx, rid, sig) {
		t.Error("unreact:v2 signature must not cross-verify as delete:v1")
	}
}

func TestBuildDeleteCanonical_DomainAndBoundary(t *testing.T) {
	c := BuildDeleteCanonical("room", "rm", "msg")
	if string(c[:len("delete:v1")]) != "delete:v1" {
		t.Errorf("missing delete:v1 domain tag: %q", c)
	}
	// Length-prefixing keeps field boundaries unambiguous: shifting a byte
	// across the kind/contextID boundary must change the signed bytes.
	a := BuildDeleteCanonical("room", "Xmsg", "y")
	b := BuildDeleteCanonical("roomX", "msg", "y")
	if string(a) == string(b) {
		t.Error("length-prefixing must keep field boundaries unambiguous")
	}
}

func TestDecodeEd25519Signature(t *testing.T) {
	good := base64.StdEncoding.EncodeToString(make([]byte, ed25519.SignatureSize))
	if _, err := DecodeEd25519Signature(good); err != nil {
		t.Errorf("valid-length signature: %v", err)
	}
	if _, err := DecodeEd25519Signature("!!not base64!!"); err == nil {
		t.Error("garbage base64 must error")
	}
	short := base64.StdEncoding.EncodeToString(make([]byte, 10))
	if _, err := DecodeEd25519Signature(short); err == nil {
		t.Error("wrong-length signature must error")
	}
}

func TestParseSSHEd25519PubKey(t *testing.T) {
	pub, _, _ := ed25519.GenerateKey(nil)
	sshPub, err := ssh.NewPublicKey(pub)
	if err != nil {
		t.Fatal(err)
	}
	authKey := string(ssh.MarshalAuthorizedKey(sshPub))
	got, err := ParseSSHEd25519PubKey(authKey)
	if err != nil {
		t.Fatalf("parse valid ed25519 authorized_key: %v", err)
	}
	if !got.Equal(pub) {
		t.Error("parsed key does not match original")
	}
	if _, err := ParseSSHEd25519PubKey("not a key"); err == nil {
		t.Error("garbage authorized_key must error")
	}
}

// TestDeleteConformanceVectors is the cross-repo interop contract: the server's
// INDEPENDENT BuildDeleteCanonical/VerifyDelete must reproduce the committed
// golden vectors (generated by sshkey-term's SignDelete, the shipped reference
// signer). A one-byte divergence in the canonical form fails here — which is
// exactly what would otherwise silently reject every legitimate delete.
func TestDeleteConformanceVectors(t *testing.T) {
	raw, err := os.ReadFile("testdata/delete_conformance_vectors.json")
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}
	var doc struct {
		Tag     string `json:"tag"`
		Vectors []struct {
			Note         string `json:"note"`
			SeedB64      string `json:"seed_b64"`
			Kind         string `json:"kind"`
			ContextID    string `json:"context_id"`
			MsgID        string `json:"msg_id"`
			CanonicalB64 string `json:"canonical_b64"`
			SignatureB64 string `json:"signature_b64"`
		} `json:"vectors"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("unmarshal vectors: %v", err)
	}
	if doc.Tag != "delete:v1" {
		t.Fatalf("unexpected tag %q", doc.Tag)
	}
	if len(doc.Vectors) == 0 {
		t.Fatal("no vectors loaded")
	}
	for _, v := range doc.Vectors {
		seed, err := base64.StdEncoding.DecodeString(v.SeedB64)
		if err != nil || len(seed) != ed25519.SeedSize {
			t.Fatalf("%s: bad seed", v.Note)
		}
		priv := ed25519.NewKeyFromSeed(seed)
		pub := priv.Public().(ed25519.PublicKey)

		wantCanon, _ := base64.StdEncoding.DecodeString(v.CanonicalB64)
		if got := BuildDeleteCanonical(v.Kind, v.ContextID, v.MsgID); string(got) != string(wantCanon) {
			t.Errorf("%s: canonical mismatch\n got  %x\n want %x", v.Note, got, wantCanon)
		}
		sig, err := base64.StdEncoding.DecodeString(v.SignatureB64)
		if err != nil {
			t.Fatalf("%s: bad signature b64", v.Note)
		}
		if !VerifyDelete(pub, v.Kind, v.ContextID, v.MsgID, sig) {
			t.Errorf("%s: golden signature failed to verify — canonical-form drift from the client", v.Note)
		}
	}
}

// TestUnreactConformanceVectors is the unreact:v2 sibling of the delete vector
// test. The unreact canonical form reuses the exact same length-prefixed
// AppendField machinery (already pinned by the delete vector) — what THIS adds is
// a cross-repo lock on the parts that differ: the "unreact:v2" domain tag and the
// (kind, contextID, reaction_id) field order. A tag typo or field reorder made on
// only one side of the repo boundary passes both repos' same-repo unit tests but
// fails here, exactly as it would silently reject every legitimate un-react.
func TestUnreactConformanceVectors(t *testing.T) {
	raw, err := os.ReadFile("testdata/unreact_conformance_vectors.json")
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}
	var doc struct {
		Tag     string `json:"tag"`
		Vectors []struct {
			Note         string `json:"note"`
			SeedB64      string `json:"seed_b64"`
			Kind         string `json:"kind"`
			ContextID    string `json:"context_id"`
			ReactionID   string `json:"reaction_id"`
			CanonicalB64 string `json:"canonical_b64"`
			SignatureB64 string `json:"signature_b64"`
		} `json:"vectors"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("unmarshal vectors: %v", err)
	}
	if doc.Tag != "unreact:v2" {
		t.Fatalf("unexpected tag %q", doc.Tag)
	}
	if len(doc.Vectors) == 0 {
		t.Fatal("no vectors loaded")
	}
	for _, v := range doc.Vectors {
		seed, err := base64.StdEncoding.DecodeString(v.SeedB64)
		if err != nil || len(seed) != ed25519.SeedSize {
			t.Fatalf("%s: bad seed", v.Note)
		}
		priv := ed25519.NewKeyFromSeed(seed)
		pub := priv.Public().(ed25519.PublicKey)

		wantCanon, _ := base64.StdEncoding.DecodeString(v.CanonicalB64)
		if got := BuildUnreactCanonical(v.Kind, v.ContextID, v.ReactionID); string(got) != string(wantCanon) {
			t.Errorf("%s: canonical mismatch\n got  %x\n want %x", v.Note, got, wantCanon)
		}
		sig, err := base64.StdEncoding.DecodeString(v.SignatureB64)
		if err != nil {
			t.Fatalf("%s: bad signature b64", v.Note)
		}
		if !VerifyUnreact(pub, v.Kind, v.ContextID, v.ReactionID, sig) {
			t.Errorf("%s: golden signature failed to verify — canonical-form drift from the client", v.Note)
		}
	}
}
